### PR TITLE
feat: #308 invoice details format date and rearrange data

### LINKED ISSUE #308: Improvements on the invoice detail page
- top left box need rearrangement 
- Bellow it the boxes we want them standardized
- Add word Invoice to the download button
- Extend the time line box to the with of the page, so it looks nicer
- if possible add a human readable time stamp of how much time passed since the data displayed.

Screen Shot 2021-08-12 at 7 30 30 AM

### PR DESCRIPTION
**Pull request by acidbiscuit**
- Re-arrange invoice details
- Add human readable date format for timeline

Closes #308

### CODE REVIEW

**Review by davidgatti — CHANGES_REQUESTED** [review]
Small running

Screen Shot 2021-08-21 at 3 17 12 PM

**Comment by acidbiscuit** [comment]
@davidgatti 

Check updated version. Note there is no option to add direction arrows to Vuetify Timeline component.

**Review by davidgatti — CHANGES_REQUESTED** [review]
- center the tag
- make arrow for time direction

Screen Shot 2021-08-21 at 5 57 30 PM

**Comment by acidbiscuit** [comment]
@davidgatti 
Check updated version

- Add timeline direction
- Center invoice status chip

**Pull request merged**
