### PR TITLE
feat: #300 invoices use updated data

### LINKED ISSUE #300: New way to display the invoice
I think I did figure out the invoice situation, Stripe is not making it easy. So now there is a new entry in the DDB as you can see bellow:

Screen Shot 2021-06-21 at 8 31 23 AM

And inside it, there is this data:

```
{
  "amount_due": 100,
  "amount_paid": 0,
  "amount_remaining": 100,
  "created": "2021-06-20T04:50:19Z",
  "invoice_pdf": null,
  "pk": "us-east-1:ec69d0d8-40da-4a66-bd3c-48c558741ccb",
  "sk": "invoice#summary#2021#06#in_1J4IbvG1wg42NuVovJ0adK2Q",
  "type": "invoice.created"
}
```

That we for now want to display as the main information for the invoice. Don't display the PK and SK, but display the rest as is, and then we will take it from there.

You still have the invoice count summary:

```
{
  "count": 1,
  "pk": "us-east-1:ec69d0d8-40da-4a66-bd3c-48c558741ccb",
  "sk": "stats#invoice#summary"
}
```

To know how many invoice will be present.

I have more data that can be displayed as the full history of the invoice, but we will add it once we have this basic info first, and then I will think how to display all the historically data of the state of the invoice, since there is quite the amount of data, but as of now I'm not sure sure what to keep and what to discard.

### PR DESCRIPTION
**Pull request by acidbiscuit**
- Display new information for invoices list: type, invoice_pdf
- Remove previous fields: invoice_id, charge_id, next_payment_attempt
- Prevent opening of single invoice page due to missing invoice id

Closes #300

### CODE REVIEW

**Comment by acidbiscuit** [comment]
@davidgatti 
So I've removed a method to check for invoices stats, since there is no data being returned for a specific year (e.g. `stats#invoice#summary#2020`) and we need to display if next page is available in the table.

Now we make 2 requests for invoices during initial load. We request data for current year and the previous year. If previous year has items available, next page button will be enabled and user can open the next page with data already loaded. No second request is made.

**Comment by davidgatti** [comment]
## Stats

The stats have now a different SK, this is the new one `stats#invoice#2021`

## Invoice ID

The invoice ID is in the SK itself, you have to extract it: `invoice#in_1J9P2MG1wg42NuVoQbuNAujg#evt_1J9P2MG1wg42NuVovkRXyYkQ`

## Id column

After the column with the download PDF, add the Invoice ID column with a click to copy.

**Review by davidgatti — CHANGES_REQUESTED** [review]
## Stats

The stats have now a different SK, this is the new one `stats#invoice#2021`

## Invoice ID

The invoice ID is in the SK itself, you have to extract it: `invoice#in_1J9P2MG1wg42NuVoQbuNAujg#evt_1J9P2MG1wg42NuVovkRXyYkQ`

## Id column

After the column with the download PDF, add the Invoice ID column with a click to copy.

**Comment by acidbiscuit** [comment]
@davidgatti Please, check update version with InvoiceId and stats.

**Comment by davidgatti** [comment]
@acidbiscuit looks good, will you do pagination next?

**Comment by acidbiscuit** [comment]
@davidgatti Pagination is already included in the latest commit. Are you having any issues?

**Comment by davidgatti** [comment]
Hmm ok, let me do some more tests.

**Pull request merged**
